name: Waka Readme

on:
  # Trigger the workflow manually or on a schedule
  workflow_dispatch:
  schedule:
    # Runs at 12 AM UTC (5:30 AM IST)
    - cron: "0 0 * * *"

jobs:
  # Job to update workflows
  update-workflows:
    name: Update Workflows
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v2
      
      # Add steps to update any necessary workflows here

  # Job to update README.md
  update-readme:
    name: Update README.md with WakaTime DevMetrics
    runs-on: ubuntu-latest
    needs: update-workflows  # Depend on the update-workflows job
    steps:
      - name: Check out the code
        uses: actions/checkout@v2
      
      - name: Update README.md with WakaTime DevMetrics
        uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SHOW_TITLE: false
          BLOCKS: ⣀⣄⣤⣦⣶⣷⣿
          TIME_RANGE: all_time
          LANG_COUNT: 6
          SHOW_TIME: true
